{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\n01-初步使用.py:5: AssertionError"}, "start": 1719211410822, "stop": 1719211410823, "uuid": "65ce803c-3a62-4c43-b422-a1131d8265cf", "historyId": "51c60bbaae7a50d9089304a72ac06e39", "testCaseId": "51c60bbaae7a50d9089304a72ac06e39", "fullName": "01-初步使用#test_answer", "labels": [{"name": "suite", "value": "01-初步使用"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "17180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "01-初步使用"}]}