{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <python_pytest.01-初步使用.TestClass object at 0x000001CC16A0AE88>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\n01-初步使用.py:14: AssertionError"}, "start": 1719211410841, "stop": 1719211410841, "uuid": "5f5f6335-4849-41ae-8447-ff4f1e801e4b", "historyId": "4a79448870e92065e8ded54fa68c7d1c", "testCaseId": "4a79448870e92065e8ded54fa68c7d1c", "fullName": "01-初步使用.TestClass#test_two", "labels": [{"name": "suite", "value": "01-初步使用"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "17180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "01-初步使用"}]}